### ISSUE TITLE
How to add paginator?

### ISSUE THREAD

**Issue by vostrikov** [ripaclub/sphinxsearch#37]

**Comment by leogr** [comment]
In order to work with `Zend\Paginator` you need to implement your own paginator adapter (in a similar way the [`Zend\Paginator\Adapter\DbSelect`](https://github.com/zendframework/zf2/blob/master/library/Zend/Paginator/Adapter/DbSelect.php) does).
Also, you can use:
```php
$search = new SphinxSearch\Search(....);
//.... your query .....
$count = $search->showMeta('total_found');
```
to the get the total results count.

Let me know if you that will help you.

**Comment by vostrikov** [comment]
Thank, I created a pagination class extended Zend\Paginator\Adapter\DbSelect
