### ISSUE TITLE
Do not understand the installation this API

### ISSUE THREAD

**Issue by fadjrin** [ripaclub/sphinxsearch#48]
hi , I am new in zf2 . how to run this API because until now I can not run, someone to help me?

**Comment by gianarb** [comment]
Hello @fadjrin 
this is not a real module but it's a library, into the README.md there are few tricks but if you are new maybe it's not easy to understand. I will try to explain step by step.

1) open your module.config.php file and add this two line into the service_locator configuration.
In this step you are configurating the sphinxql service.

``` php
'factories' => [
    'SphinxSearch\Db\Adapter\Adapter' => 'SphinxSearch\Db\Adapter\AdapterServiceFactory'
],
'aliases' => [
    'sphinxql' => 'SphinxSearch\Db\Adapter\Adapter'
]
```

2) Open your `local.php` to store your sphinx credentials, this file is not into the vcs because it's not good store password in git.

``` php
'sphinxql' => [
        'driver'    => 'pdo_mysql',
        'hostname'  => '127.0.0.1',
        'port'      => 9306,
        'charset'   => 'UTF8'
]
```

At this point if all it's good you can use the service manager around your application to speech with sphinx. If you are inside a controller you can do something like:
`$this->getServiceLocator()->get('sphinxql');`

**Comment by fadjrin** [comment]
until here I have understood , but when accessing data message like this and my confusion to overcome
![screenshot from 2016-06-03 16-36-51](https://cloud.githubusercontent.com/assets/311463/15774989/8c19b940-29a9-11e6-81d4-23e877ac1e44.png)

this my source code.

`       public function test123Action()
       {

```
     $adapter = $this->getServiceLocator()->get('sphinxql');
```

$search = new Search($adapter);
$rowset = $search->search('TLKM');

```
    die(var_dump($rowset));
   }`
```

**Comment by gianarb** [comment]
Your problem is not relative this flow I think.. or maybe yes but you can not render the error page and we can not read the proper exception. Fix this problem before.. Try to remove 

`$adapter = $this->getServiceLocator()->get('sphinxql');`

and throw an exception, I will have the same problem

**Comment by fadjrin** [comment]
my problem Happens When I call a search function

**Comment by fadjrin** [comment]
when i remark this function app show it message

**Comment by gianarb** [comment]
Can you try to remove all your code from this action and throw an Execption, just

```
throw new \Exception
```

do you have the same problem?

**Comment by fadjrin** [comment]
thx @gianarb i solve my problem with your solution. during this time I can not see detail error

**Comment by leodido** [comment]
Can I close @gianarb ?
